### ISSUE TITLE
Array as a key of a map does not work

### ISSUE THREAD

**Issue by bichanna** [Gen-lang/Gen#30]
This code does not work:
```
map = {[1, 2, 3]: "something"}
```

**Comment by bichanna** [comment]
```
Traceback (most recent call last):
  File "/Users/nobu/WorkSpace/Python/Gen/pygen/main.py", line 96, in <module>
    shell()
  File "/Users/nobu/WorkSpace/Python/Gen/pygen/main.py", line 68, in shell
    result, err = run("<stdin>", t)
  File "/Users/nobu/WorkSpace/Python/Gen/pygen/main.py", line 59, in run
    result = evaluator.visit(ast.node, context)
  File "/Users/nobu/WorkSpace/Python/Gen/pygen/src/evaluator.py", line 57, in visit
    if only_return_symtable is False: return method(node, context)
  File "/Users/nobu/WorkSpace/Python/Gen/pygen/src/evaluator.py", line 216, in visit_ArrayNode
    elements.append(res.register(self.visit(element, context)))
  File "/Users/nobu/WorkSpace/Python/Gen/pygen/src/evaluator.py", line 57, in visit
    if only_return_symtable is False: return method(node, context)
  File "/Users/nobu/WorkSpace/Python/Gen/pygen/src/evaluator.py", line 224, in visit_MapNode
    map[key.token.value] = res.register(self.visit(v, context))
AttributeError: 'ArrayNode' object has no attribute 'token'
```

**Comment by GalaxianMonster** [comment]
I don't think a map should contain an array as a key.

**Comment by bichanna** [comment]
Okay, I'll throw an error there, not a Python one.
